#!/usr/bin/env bash

echo -e "\nInstalling [Neo]Vim dotfiles.\n"

# initialize paq
PACKPATH="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/pack/packer/start"
mkdir -p "${PACKPATH}"

if [ -d "${PACKPATH}/packer.nvim" ]
then
    echo Paq-nvim already exists
else
    echo cloning...
    # git clone https://github.com/savq/paq-nvim.git "${PACKPATH}/paq-nvim"
    git clone "https://github.com/wbthomason/packer.nvim" "${PACKPATH}/packer.nvim"
fi
